<a href="https://colab.research.google.com/github/TinkerTechie/LLM_LEARNING/blob/main/tokenembedding2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import torch
input_ids = torch.tensor([2,3,5,1])

we are doing embedding here we will get every vector embedding of dimension 3 and vocabulary size for this embedding model will be 8

In [4]:
voacb_size = 8
output_dim = 3
torch.manual_seed(123)
embedding_layer = torch.nn.Embedding(voacb_size,output_dim)

In [5]:
print(embedding_layer.weight)

Parameter containing:
tensor([[ 0.3374, -0.1778, -0.3035],
        [-0.5880,  0.3486,  0.6603],
        [-0.2196, -0.3792, -0.1606],
        [-0.4015,  0.6957, -1.8061],
        [ 1.8960, -0.1750,  1.3689],
        [-1.6033, -0.7849, -1.4096],
        [-0.4076,  0.7953,  0.9985],
        [ 0.2212,  1.8319, -0.3378]], requires_grad=True)


get the vector for the given id as it is staring from 0th index


In [6]:
print(embedding_layer(torch.tensor(3)))

tensor([-0.4015,  0.6957, -1.8061], grad_fn=<EmbeddingBackward0>)


In [7]:
print(embedding_layer(input_ids))

tensor([[-0.2196, -0.3792, -0.1606],
        [-0.4015,  0.6957, -1.8061],
        [-1.6033, -0.7849, -1.4096],
        [-0.5880,  0.3486,  0.6603]], grad_fn=<EmbeddingBackward0>)
